"""Engine, refrigerator, accelerator or heater? Mapping operation modes.

Left: the quasi-static single-qubit Otto cycle. The only modes are engine and
refrigerator, separated exactly by w_c/w_h = T_c/T_h (the dashed line).

Right: the same cycle run in finite time with a drive that does not commute
with itself at different times (a transverse field). Quantum friction --
coherence generated by the fast ramps and then destroyed by the baths --
costs work, and the accelerator and heater modes take over large parts of
the diagram (cf. Solfanelli, Falsetti & Campisi, PRB 101, 054513 (2020)).

    python examples/operation_modes.py
"""

import pathlib

import numpy as np

import qthermo as qt

FIGURES = pathlib.Path(__file__).resolve().parent / "figures"
ratios = np.linspace(0.08, 0.95, 14)


def ideal(w_ratio, t_ratio):
    return qt.ideal_otto(qt.qubit_hamiltonian(w_ratio), qt.qubit_hamiltonian(1.0),
                         t_ratio, 1.0)


def finite_time(w_ratio, t_ratio, delta=0.4, tau_ramp=0.3):
    H = lambda w: qt.qubit_hamiltonian(w) + delta * qt.sigma_x
    # Two coupling channels so the isochores thermalise fully at every point:
    # the modes on the right come from the fast ramps, not from the baths.
    return qt.otto_cycle(H(w_ratio), H(1.0), t_ratio, 1.0, [qt.sigma_x, qt.sigma_z],
                         gamma=1.0, tau_iso=15.0, tau_ramp=tau_ramp, steps=150)


quasi_static = qt.mode_map(ideal, ratios, ratios, parameters=("w_c / w_h", "T_c / T_h"))
fast = qt.mode_map(finite_time, ratios, ratios, parameters=("w_c / w_h", "T_c / T_h"))

for name, scan in (("quasi-static", quasi_static), ("finite time", fast)):
    codes, counts = np.unique(scan.grid, return_counts=True)
    share = ", ".join(f"{qt.MODES[int(c)]} {n / scan.grid.size:.0%}"
                      for c, n in zip(codes, counts))
    print(f"{name:>13}: {share}")

X, Y = np.meshgrid(quasi_static.x_values, quasi_static.y_values)
engine = quasi_static.grid == qt.MODES.index("engine")
print("quasi-static engine region is exactly w_c/w_h > T_c/T_h:",
      bool(np.array_equal(engine, X > Y + 1e-12)))

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
except ImportError:
    raise SystemExit("(matplotlib not installed: skipping figure)")

fig, axes = plt.subplots(1, 2, figsize=(10, 4.2))
qt.plot_mode_map(quasi_static, ax=axes[0])
axes[0].plot([0, 1], [0, 1], "w--", lw=1.2)
axes[0].set_xlim(ratios[0], ratios[-1]); axes[0].set_ylim(ratios[0], ratios[-1])
axes[0].set_title("Quasi-static qubit Otto cycle", fontsize=10)
qt.plot_mode_map(fast, ax=axes[1])
axes[1].set_title("Finite time, non-commuting drive", fontsize=10)
fig.tight_layout()
FIGURES.mkdir(exist_ok=True)
fig.savefig(FIGURES / "operation_modes.png", dpi=130, bbox_inches="tight")
print(f"figure written to {FIGURES / 'operation_modes.png'}")
